### PR TITLE
Fix turret deadzone at 50 degrees

### LINKED ISSUE #576: Fix turret dead zone at 50 degrees
The turret setAngle has an issue that clamps any angle between 50 and 60 to 50 degrees.

### PR DESCRIPTION
**Pull request by mavanie**
Moved modulo logic into optimized turret angle. Remove clamp.
Tested in sim

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Turret.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ public Turret(Swerve drivetrain) {
             gearbox = DCMotor.getKrakenX44Foc(1);
             turretSim = new SingleJointedArmSim(gearbox, TurretConstants.ENCODER_TO_MECHANISM_RATIO,
                     TurretConstants.MOI.in(KilogramSquareMeters), TurretConstants.LENGTH.in(Meters),
-                    TurretConstants.MIN_ANGLE.in(Radians), TurretConstants.MAX_ANGLE.in(Radians),
+                    -TurretConstants.MAX_ANGLE.in(Radians), -TurretConstants.MIN_ANGLE.in(Radians),
```
Comment (mavanie) [inline src/main/java/frc/robot/subsystems/Turret.java:175]: Needed to fix sim.

**Review by Vilok1 — APPROVED** [review]

**Review by aaditst — APPROVED** [review]
lgtm
